// export const GET_ALL_PATIENTDETAILS_REQUEST = 'products/GET_ALL_PATIENTDETAILS_REQUEST';
// export const GET_ALL_PATIENTDETAILS_SUCCESS = 'products/GET_ALL_PATIENTDETAILS_SUCCESS';
// export const GET_ALL_PATIENTDETAILS_FAILURE = 'products/GET_ALL_PATIENTDETAILS_FAILURE';

// //on single product page
export const GET_SINGLE_LEAVE_REQUEST = 'LEAVE/GET_SINGLE_LEAVE_REQUEST';
export const GET_SINGLE_LEAVE_SUCCESS = 'LEAVE/GET_SINGLE_LEAVE_SUCCESS';
export const GET_SINGLE_LEAVE_FAILURE = 'LEAVE/GET_SINGLE_LEAVE_FAILURE';

//used
export const GET_EMP_LEAVE_REQUEST = 'LEAVE/GET_EMP_LEAVE_REQUEST';
export const GET_EMP_LEAVE_SUCCESS = 'LEAVE/GET_EMP_LEAVE_SUCCESS';
export const GET_EMP_LEAVE_FAILURE = 'LEAVE/GET_EMP_LEAVE_FAILURE';


//for add asset 
export const ADD_LEAVE_REQUEST = 'LEAVE/ADD_LEAVE_REQUEST';
export const ADD_LEAVE_SUCCESS = 'LEAVE/ADD_LEAVE_SUCCESS';
export const ADD_LEAVE_FAILURE = 'LEAVE/ADD_LEAVE_FAILURE';

//for admin only
export const UPDATE_LEAVE_REQUEST = 'LEAVE/UPDATE_PRODUCT_REQUEST';
export const UPDATE_LEAVE_SUCCESS = 'LEAVE/UPDATE_PRODUCT_SUCCESS';
export const UPDATE_LEAVE_FAILURE = 'LEAVE/UPDATE_PRODUCT_FAILURE';


// export const UPDATE_PRODUCT_REQUEST1 = 'products/UPDATE_PRODUCT_REQUEST1';
// export const UPDATE_PRODUCT_SUCCESS1 = 'products/UPDATE_PRODUCT_SUCCESS1';
// export const UPDATE_PRODUCT_FAILURE1 = 'products/UPDATE_PRODUCT_FAILURE1';

//for admin only
export const DELETE_LEAVE_REQUEST = 'LEAVE/DELETE_LEAVE_REQUEST';
export const DELETE_LEAVE_SUCCESS = 'LEAVE/DELETE_LEAVE_SUCCESS';
export const DELETE_LEAVE_FAILURE = 'LEAVE/DELETE_LEAVE_FAILURE';

// export const DELETE_OPPOINTMENT_REQUEST = 'products/DELETE_OPPOINTMENT_REQUEST';
// export const DELETE_OPPOINTMENT_SUCCESS = 'products/DELETE_OPPOINTMENT_SUCCESS';
// export const DELETE_OPPOINTMENT_FAILURE = 'products/DELETE_OPPOINTMENT_FAILURE';


//for employee id asset 
// export const GET_AUTHOR_PRODUCT_REQUEST1 = 'products/GET_AUTHOR_PRODUCT_REQUEST1';
// export const GET_AUTHOR_PRODUCT_SUCCESS2 = 'products/GET_AUTHOR_PRODUCT_SUCCESS2';
// export const GET_AUTHOR_PRODUCT_FAILURE3 = 'products/GET_AUTHOR_PRODUCT_FAILURE3';


// export const GET_EMP_ASSET_REQUEST1 = 'products/GET_AUTHOR_PRODUCT1_REQUEST1';
// export const GET_EMP_ASSET_SUCCESS2 = 'products/GET_AUTHOR_PRODUCT1_SUCCESS2';
// export const GET_EMP_ASSET_FAILURE3 = 'products/GET_AUTHOR_PRODUCT1_FAILURE3';
