// export const GET_ALL_PATIENTDETAILS_REQUEST = 'products/GET_ALL_PATIENTDETAILS_REQUEST';
// export const GET_ALL_PATIENTDETAILS_SUCCESS = 'products/GET_ALL_PATIENTDETAILS_SUCCESS';
// export const GET_ALL_PATIENTDETAILS_FAILURE = 'products/GET_ALL_PATIENTDETAILS_FAILURE';

// //on single product page
// export const GET_SINGLE_PRODUCT_REQUEST = 'products/GET_SINGLE_PRODUCT_REQUEST';
// export const GET_SINGLE_PRODUCT_SUCCESS = 'products/GET_SINGLE_PRODUCT_SUCCESS';
// export const GET_SINGLE_PRODUCT_FAILURE = 'products/GET_SINGLE_PRODUCT_FAILURE';

//used
export const GET_EMP_RESIGN_REQUEST = 'RESIGN/GET_EMP_JOB_REQUEST';
export const GET_EMP_RESIGN_SUCCESS = 'RESIGN/GET_EMP_JOB_SUCCESS';
export const GET_EMP_RESIGN_FAILURE = 'RESIGN/GET_EMP_JOB_FAILURE';


//for add asset 
export const ADD_RESIGN_REQUEST = 'RESIGN/ADD_TICKET_REQUEST';
export const ADD_RESIGN_SUCCESS = 'RESIGN/ADD_TICKET_SUCCESS';
export const ADD_RESIGN_FAILURE = 'RESIGN/ADD_TICKET_FAILURE';

//for admin only
export const UPDATE_RESIGN_REQUEST = 'RESIGN/UPDATE_RESIGN_REQUEST';
export const UPDATE_RESIGN_SUCCESS = 'RESIGN/UPDATE_RESIGN_SUCCESS';
export const UPDATE_RESIGN_FAILURE = 'RESIGN/UPDATE_RESIGN_FAILURE';


// export const UPDATE_PRODUCT_REQUEST1 = 'products/UPDATE_PRODUCT_REQUEST1';
// export const UPDATE_PRODUCT_SUCCESS1 = 'products/UPDATE_PRODUCT_SUCCESS1';
// export const UPDATE_PRODUCT_FAILURE1 = 'products/UPDATE_PRODUCT_FAILURE1';

//for admin only
export const DELETE_RESIGN_REQUEST = 'RESIGN/DELETE_TICKET_REQUEST';
export const DELETE_RESIGN_SUCCESS = 'RESIGN/DELETE_TICKET_SUCCESS';
export const DELETE_RESIGN_FAILURE = 'RESIGN/DELETE_TICKET_FAILURE';

// export const DELETE_OPPOINTMENT_REQUEST = 'products/DELETE_OPPOINTMENT_REQUEST';
// export const DELETE_OPPOINTMENT_SUCCESS = 'products/DELETE_OPPOINTMENT_SUCCESS';
// export const DELETE_OPPOINTMENT_FAILURE = 'products/DELETE_OPPOINTMENT_FAILURE';


//for employee id asset 
// export const GET_AUTHOR_PRODUCT_REQUEST1 = 'products/GET_AUTHOR_PRODUCT_REQUEST1';
// export const GET_AUTHOR_PRODUCT_SUCCESS2 = 'products/GET_AUTHOR_PRODUCT_SUCCESS2';
// export const GET_AUTHOR_PRODUCT_FAILURE3 = 'products/GET_AUTHOR_PRODUCT_FAILURE3';


// export const GET_EMP_ASSET_REQUEST1 = 'products/GET_AUTHOR_PRODUCT1_REQUEST1';
// export const GET_EMP_ASSET_SUCCESS2 = 'products/GET_AUTHOR_PRODUCT1_SUCCESS2';
// export const GET_EMP_ASSET_FAILURE3 = 'products/GET_AUTHOR_PRODUCT1_FAILURE3';
