// export const GET_ALL_PATIENTDETAILS_REQUEST = 'products/GET_ALL_PATIENTDETAILS_REQUEST';
// export const GET_ALL_PATIENTDETAILS_SUCCESS = 'products/GET_ALL_PATIENTDETAILS_SUCCESS';
// export const GET_ALL_PATIENTDETAILS_FAILURE = 'products/GET_ALL_PATIENTDETAILS_FAILURE';

// //on single product page
// export const GET_SINGLE_PRODUCT_REQUEST = 'products/GET_SINGLE_PRODUCT_REQUEST';
// export const GET_SINGLE_PRODUCT_SUCCESS = 'products/GET_SINGLE_PRODUCT_SUCCESS';
// export const GET_SINGLE_PRODUCT_FAILURE = 'products/GET_SINGLE_PRODUCT_FAILURE';

//used
export const GET_EMP_PROJECT_REQUEST = 'project/GET_EMP_PROJECT_REQUEST';
export const GET_EMP_PROJECT_SUCCESS = 'project/GET_EMP_PROJECT_SUCCESS';
export const GET_EMP_PROJECT_FAILURE = 'project/GET_EMP_PROJECT_FAILURE';

export const GET_EMP_ASSIGNEDPROJECT_REQUEST = 'project/GET_EMP_ASSIGNEDPROJECT_REQUEST';
export const GET_EMP_ASSIGNEDPROJECT_SUCCESS = 'project/GET_EMP_ASSIGNEDPROJECT_SUCCESS';
export const GET_EMP_ASSIGNEDPROJECT_FAILURE = 'project/GET_EMP_ASSIGNEDPROJECT_FAILURE';

export const GET_EMP_PASTPROJECT_REQUEST = 'project/GET_EMP_PASTPROJECT_REQUEST';
export const GET_EMP_PASTPROJECT_SUCCESS = 'project/GET_EMP_PASTPROJECT_SUCCESS';
export const GET_EMP_PASTPROJECT_FAILURE = 'project/GET_EMP_PASTPROJECT_FAILURE';


export const GET_EMP_PROJECT_REQUEST1 = 'project/GET_EMP_PROJECT_REQUEST1';
export const GET_EMP_PROJECT_SUCCESS1 = 'project/GET_EMP_PROJECT_SUCCESS1';
export const GET_EMP_PROJECT_FAILURE1 = 'project/GET_EMP_PROJECT_FAILURE1';

//for add asset 
export const ADD_PROJECT_REQUEST = 'project/ADD_PROJECT_REQUEST';
export const ADD_PROJECT_SUCCESS = 'project/ADD_PROJECT_SUCCESS';
export const ADD_PROJECT_FAILURE = 'project/ADD_PROJECT_FAILURE';

//for admin only
export const UPDATE_PROJECT_REQUEST = 'PROJECT/UPDATE_PROJECT_REQUEST';
export const UPDATE_PROJECT_SUCCESS = 'PROJECT/UPDATE_PROJECT_SUCCESS';
export const UPDATE_PROJECT_FAILURE = 'PROJECT/UPDATE_PROJECT_FAILURE';


// export const UPDATE_PRODUCT_REQUEST1 = 'products/UPDATE_PRODUCT_REQUEST1';
// export const UPDATE_PRODUCT_SUCCESS1 = 'products/UPDATE_PRODUCT_SUCCESS1';
// export const UPDATE_PRODUCT_FAILURE1 = 'products/UPDATE_PRODUCT_FAILURE1';

// //for admin only
export const DELETE_PROJECT_REQUEST = 'PROJECT/DELETE_PROJECT_REQUEST';
export const DELETE_PROJECT_SUCCESS = 'PROJECT/DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAILURE = 'PROJECT/DELETE_PROJECT_FAILURE';

// export const DELETE_OPPOINTMENT_REQUEST = 'products/DELETE_OPPOINTMENT_REQUEST';
// export const DELETE_OPPOINTMENT_SUCCESS = 'products/DELETE_OPPOINTMENT_SUCCESS';
// export const DELETE_OPPOINTMENT_FAILURE = 'products/DELETE_OPPOINTMENT_FAILURE';


//for employee id asset 
// export const GET_AUTHOR_PRODUCT_REQUEST1 = 'products/GET_AUTHOR_PRODUCT_REQUEST1';
// export const GET_AUTHOR_PRODUCT_SUCCESS2 = 'products/GET_AUTHOR_PRODUCT_SUCCESS2';
// export const GET_AUTHOR_PRODUCT_FAILURE3 = 'products/GET_AUTHOR_PRODUCT_FAILURE3';


// export const GET_EMP_ASSET_REQUEST1 = 'products/GET_AUTHOR_PRODUCT1_REQUEST1';
// export const GET_EMP_ASSET_SUCCESS2 = 'products/GET_AUTHOR_PRODUCT1_SUCCESS2';
// export const GET_EMP_ASSET_FAILURE3 = 'products/GET_AUTHOR_PRODUCT1_FAILURE3';
